CREATE TABLE users
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(256),
    age INTEGER,
    insert_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);